name: "Hello Actions"
description: "Greeta Thunberg"
author: "Loukas K."

inputs:
    MY_NAME:
        description: "Who the script will greet"
        required: true
        default: "World"

runs:
    using: "docker"
    image: "Dockerfile"

branding:
    icon: "mic"
    color: "purple"
